import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Início | Larissa Silva</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <p>Whereas recognition of the inherent dignity</p>
    </>
  );
}
