import Head from "next/head";
import { Wrapper } from "@/components/Wrapper";

import { Navigation } from "@/components/Navigation";
import { Header } from "@/components/Header";
import { Social } from "@/components/Social";

export default function Home() {
  return (
    <>
      <Head>
        <title>Início | Larissa Silva</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Wrapper>
        <Header />
        <Navigation />
        <Social />
      </Wrapper>
    </>
  );
}
